config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "escritorio#index"#get 'escritorio/index'
    resources :projects,only: [:new,:create, :destroy]

    resources :usuarios do
      member do
        patch  :deshabilitar 
      end
    end
  end

  root 'projects#index'

    resources :projects,  only: [:index,:show,:edit,:update ] do 
      resources :tickets
    end

  devise_for :users

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates  :nombre, presence: true
	has_many :tickets,dependent: :restrict_with_error#dependent: :delete_all#dependent: :destroy
	has_many :rols, dependent:  :delete_all

end

app/models/rol.rb
class Rol < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	validates :nombre, presence: true	
	validates :descripcion, presence: true,length: {minimum: 10}
  belongs_to :project
  belongs_to :autor, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :excluir_deshabilitado, lambda{ where(deshabilitado: nil) }
  def to_s
  	"#{email} (#{admin? ? "Administrador" : "Usuario" })"
  end

  def deshabilitar
  	self.update(deshabilitado: Time.now)
  end

  def active_for_authentication?
    super && deshabilitado.nil?
  end

  def inactive_message
    deshabilitado.nil? ? super: :deshabilitado
  end

end

app/controllers/admin/escritorio_controller.rb
class Admin::EscritorioController < ApplicationController
  
  before_action :autorizacion_admin!

  def index
  end

  private

  def autorizacion_admin! 
  	authenticate_user! #metodo de devise

  	unless current_user.admin?
  		redirect_to root_path, alert: "Acción solo para administradores"
  	end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::EscritorioController #class Admin::ProjectsController < ApplicationController
	before_action :set_project, only: [:destroy]
	 def new
  	@project = Project.new
  end

  def create  	
  	@project = Project.new(project_params)
	  if @project.save
      flash[:notice]= 'Proyecto fue creado'
	  	redirect_to @project
	  else
      flash.now[:alert]='Proyecto no creado'
	  	render :new
	  end
  end


  def destroy
    @project.destroy
    flash[:notice] =  "Proyecto ha sido eliminado"
    redirect_to @project
  end

  private

  def set_project
    @project = Project.find(params[:id]) 
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "Proyecto no encontrado"
      redirect_to projects_path  	
  end

  def project_params
  	params.require(:project).permit(:nombre,:descripcion)
  end

end

app/controllers/admin/usuarios_controller.rb
class Admin::UsuariosController < Admin::EscritorioController#ApplicationController
    before_action :set_user,only: [:show,:edit,:update,:deshabilitar]

  def deshabilitar
    
    if @user  == current_user
      flash[:alert] = "Esta cuenta de administrador no puede eliminarse"
    else 
    @user.deshabilitar
    flash[:notice] = "Usuario deshabilitado"      
    end

    redirect_to admin_usuarios_path
  end
    
  def index
  	@users = User.excluir_deshabilitado.order(:email)#@users =  User.order(:email)
  end

  def new
  	@user = User.new
    logger.debug "N*******************************"
    logger.debug  p @user.email
  end

  def show
  	
  end

  def edit
    logger.debug "E*******************************"
    logger.debug p @user.email
  end

  def update

    if params[:user][:password].blank?
      params[:user].delete(:password)
    end

    if @user.update(params_user)
      flash[:notice] = "User has been updated."
      redirect_to admin_usuarios_path
    else
      flash[:alert] = "User has not been updated."
      render :edit
    end
  end

  def create
  	@user  =  User.new(params_user)
  	if @user.save
  		flash[:notice] = "User has been created."
  		redirect_to admin_usuarios_path #@user
  	else
  		flash[alert] = "User has not been created."
  		render :new
  	end
  end

  private

  def set_user
  	@user = User.find(params[:id])
  end

  def params_user
  	params.require(:user).permit(:email,:password,:admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	include Pundit
	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :sin_autorizacion

  private

  def sin_autorizacion
  	redirect_to root_path, alert: "Perfil de cuenta, no permite esa acción"
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show,:edit,:update]
  def index
  	@projects = Project.all
  end

  def show  	
    authorize @project, :show?
  end


  def edit

  end


  def update
    if @project.update(project_params)
      flash[:notice] =  'Proyecto ha sido editado'
      redirect_to @project
    else
      flash[:alert] = "Proyecto presenta datos inválidos"
      render :edit
    end  	
  end

  private

  def set_project
    @project = Project.find(params[:id]) 
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "Proyecto no encontrado"
      redirect_to projects_path  	
  end
  def project_params
  	params.require(:project).permit(:nombre,:descripcion)
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_project
  before_action :set_ticket, only: [:show,:edit,:update,:destroy]
  def index
  end

  def new
  	@ticket  =  @project.tickets.build
  end

  def create
  	@ticket  = @project.tickets.build(params_ticket)
    @ticket.autor = current_user
  	if @ticket.save
  		flash[:notice] = "Ticket creado"
  		redirect_to [@project,@ticket]
  	else
  		flash[:alert] = "Ticket no creado"
  		render :new
  	end
  end

  def show
  end

  def edit
  end
  def update
    
    if @ticket.update params_ticket
      flash[:notice] =  "Ticket Guardado"
      redirect_to [@project,@ticket]
    else
      flash[:alert] = "Ticket no guardado"
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket eliminado"
    redirect_to @project
  end
private
  def set_project
  	@project = Project.find(params[:project_id])
  end

  def set_ticket
  	@ticket = @project.tickets.find(params[:id])
  end

  def params_ticket
  	params.require(:ticket).permit(:nombre,:descripcion)
  end

end

app/helpers/admin/escritorio_helper.rb
module Admin::EscritorioHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/admin/usuarios_helper.rb
module Admin::UsuariosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def titulo(*parts)
		unless parts.empty?
			content_for :titulo do
				(parts <<'Tikeg').join(' - ')
			end
		end
	end
	def solo_administrador(&block)
		block.call if  current_user.try(:admin?)
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/escritorio/index.html.erb
<h1>Escritorio administrador</h1>
<nav>
	<ul>
		<li><%= link_to "Usuarios", admin_usuarios_path %></li>
		<li>acción 2</li>
	</ul>
</nav>

app/views/admin/projects/_form.html.erb
<% if @project.errors.any? %>
	<h3>Hay <%= pluralize @project.errors.count, 'error' %>. Proyecto no creado </h3>
<% end %>
<% @project.errors.full_messages.each do |msg|  %>
	<li><%= msg %></li>
<% end %>

<%= form_for ([:admin,@project]) do |f|%>
	<%= f.label :nombre,'Nombre ticket' %>
	<%= f.text_field :nombre %> <br>
	<%= f.label :descripcion %>
	<%= f.text_field :descripcion %> <br>
	<%= f.submit 'Crear proyecto' %>
<% end %>

app/views/admin/projects/new.html.erb
<h1>Nuevo proyecto</h1>
<%= render 'form' %>

app/views/admin/usuarios/_form.html.erb
<%= form_for @user , url: @user.id ? admin_usuario_path : admin_usuarios_path , 
		method: @user.id ? :patch : :post do  |f|%>

	<%= f.label :email %>
	<%= f.text_field :email %> <br>
	<%= f.label :password %>
	<%= f.text_field :password %> <br>
	<%= f.label :admin,'Administrador?' %>
	<%= f.check_box :admin %><br>
	<%= f.submit 'Crear usuario' %> 
<% end %>

app/views/admin/usuarios/edit.html.erb
<h2>Editar usuario</h2>
<%= render 'form' %>

app/views/admin/usuarios/index.html.erb
<h1>Usuarios</h1>

<%= link_to "Nuevo usuario", new_admin_usuario_path %>
	<ul>
		<% @users.each do |u| %>
			<li><%= link_to u,admin_usuario_path(u) %></li>	
		<% end %>
	</ul>

app/views/admin/usuarios/new.html.erb
<h2>Nuevo usuario</h2>
<%= render 'form' %>

app/views/admin/usuarios/show.html.erb
<h2>Detalles usuario <%= @user.email %></h2>

<%= link_to "Editar usuario", edit_admin_usuario_path(@user) %>
<%= link_to "Deshabilitar Usuario", deshabilitar_admin_usuario_path, 
						method: :patch, data: {confirm: "Confirma deshabilitar usuario"} %>		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  	<% if content_for :titulo %>
  		<%= yield(:titulo) %>
  	<% else %>
  		Tikeg
  	<% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% unless user_signed_in? %>
  <%= link_to 'Registrarse', new_user_registration_path %>
  <%= link_to 'Ingresar', new_user_session_path %>
  <% else %>
  Signed in as <%= current_user.email %>
  <%= link_to 'Salir', destroy_user_session_path, method: :delete%>
<% end %> <br>
<% solo_administrador do %>
  <%= link_to 'Administrar', admin_root_path %>
<% end %>
<h3>
<%= notice %>
<%= alert %>
</h3>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
	<h3>Hay <%= pluralize @project.errors.count, 'error' %>. Proyecto no creado </h3>
<% end %>
<% @project.errors.full_messages.each do |msg|  %>
	<li><%= msg %></li>
<% end %>

<%= form_for @project do |f|%>
	<%= f.label :nombre,'Nombre ticket' %>
	<%= f.text_field :nombre %> <br>
	<%= f.label :descripcion %>
	<%= f.text_field :descripcion %> <br>
	<%= f.submit 'Crear proyecto' %>
<% end %>

app/views/projects/edit.html.erb
<h3>Editar proyecto</h3>
<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Lista proyectos</h1>

<% solo_administrador do %>
	<%= link_to 'Nuevo Proyecto',new_admin_project_path %> <br>
<% end %>

<% @projects.each do |p| %>
<h3><%= link_to p.nombre , p%></h3>
<%= p.descripcion %>

<% end %>

app/views/projects/show.html.erb
<% titulo @project.nombre  %>

<h2>Detalles proyecto</h2>
<h3><%= @project.nombre %></h3>
<p><%= @project.descripcion %></p>
<h3>**Tickets**</h3>
<ul>
<% @project.tickets.each do |ticket|%>
	<li><%=  link_to ticket.nombre, [@project, ticket]%> </li>
	<%= ticket.descripcion %>
	<br>
<% end %>
</ul>

<%= link_to 'Proyectos', projects_path%> <br>
<%= link_to 'Editar proyecto', edit_project_path(@project) %> <br>

<% solo_administrador do %>
	<%= link_to 'Borrar proyecto', admin_project_path(@project) , method: :delete, data: {confirm: "Confirmar eliminación?"}%>
<% end %>

<%= link_to "Nuevo ticket", new_project_ticket_path(@project) %>

app/views/tickets/_form.html.erb
<% if @ticket.errors.any? %>
	<% @ticket.errors.full_messages.each do |mensaje| %>
	<h4><%= mensaje %></h4>
	<% end %>
<% end %>

<%= form_for [@project,@ticket] do |f|%>
	<%= f.label :nombre %>
	<%= f.text_field :nombre %>
	<%= f.label :descripcion %>
	<%= f.text_field :descripcion %>	
	<%= f.submit "Crear ticket" %>
<% end %>

app/views/tickets/edit.html.erb
<h1>Tickets#edit</h1>
<%= render 'form' %>

app/views/tickets/index.html.erb
<h1>Tickets#index</h1>
<p>Find me in app/views/tickets/index.html.erb</p>

app/views/tickets/new.html.erb
<h1>Nuevo Ticket</h1>

<%= render 'form' %>

app/views/tickets/show.html.erb
<h1><%=  link_to @project.nombre, @project%></h1>
<div id="ticket">
	<p>
		<%= @ticket.nombre  %>
	</p>
	<p>
		<%= @ticket.descripcion %>
	</p>

	<p>Autor: <%= @ticket.autor.email  %></p>
	
</div>
<%= link_to "Editar ticket", edit_project_ticket_path(@project,@ticket)%>
<%= link_to "Borrar ticket", [ @project, @ticket] , method: :delete, data: {confirm: "Confirma eliminar?"} %>